//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutBase.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\GLOBE")]
        public string GLOBE_DataPath {
            get {
                return ((string)(this["GLOBE_DataPath"]));
            }
            set {
                this["GLOBE_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GLOBE_Enabled {
            get {
                return ((bool)(this["GLOBE_Enabled"]));
            }
            set {
                this["GLOBE_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.ngdc.noaa.gov/mgg/topo/DATATILES/elev/")]
        public string GLOBE_URL {
            get {
                return ((string)(this["GLOBE_URL"]));
            }
            set {
                this["GLOBE_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.ngdc.noaa.gov/mgg/topo/DATATILES/elev/\r\nhttps://www.airscout.eu/downl" +
            "oads/GLOBE")]
        public string GLOBE_URLs {
            get {
                return ((string)(this["GLOBE_URLs"]));
            }
            set {
                this["GLOBE_URLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM3")]
        public string SRTM3_DataPath {
            get {
                return ((string)(this["SRTM3_DataPath"]));
            }
            set {
                this["SRTM3_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SRTM3_Enabled {
            get {
                return ((bool)(this["SRTM3_Enabled"]));
            }
            set {
                this["SRTM3_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/")]
        public string SRTM3_URL {
            get {
                return ((string)(this["SRTM3_URL"]));
            }
            set {
                this["SRTM3_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Africa/
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Australia/
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Islands/
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/North_America/
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/South_America/")]
        public string SRTM3_URLs {
            get {
                return ((string)(this["SRTM3_URLs"]));
            }
            set {
                this["SRTM3_URLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM1")]
        public string SRTM1_DataPath {
            get {
                return ((string)(this["SRTM1_DataPath"]));
            }
            set {
                this["SRTM1_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SRTM1_Enabled {
            get {
                return ((bool)(this["SRTM1_Enabled"]));
            }
            set {
                this["SRTM1_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/")]
        public string SRTM1_URL {
            get {
                return ((string)(this["SRTM1_URL"]));
            }
            set {
                this["SRTM1_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_01
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_02
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_03
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_04
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_05
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_06
https://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_07")]
        public string SRTM1_URLs {
            get {
                return ((string)(this["SRTM1_URLs"]));
            }
            set {
                this["SRTM1_URLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Database_Directory {
            get {
                return ((string)(this["Database_Directory"]));
            }
            set {
                this["Database_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Database_InMemory {
            get {
                return ((bool)(this["Database_InMemory"]));
            }
            set {
                this["Database_InMemory"] = value;
            }
        }
    }
}
