//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirScoutDatabaseManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public double MinLon {
            get {
                return ((double)(this["MinLon"]));
            }
            set {
                this["MinLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxLon {
            get {
                return ((double)(this["MaxLon"]));
            }
            set {
                this["MaxLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double MinLat {
            get {
                return ((double)(this["MinLat"]));
            }
            set {
                this["MinLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double MaxLat {
            get {
                return ((double)(this["MaxLat"]));
            }
            set {
                this["MaxLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenStreetMap")]
        public string Map_Provider {
            get {
                return ((string)(this["Map_Provider"]));
            }
            set {
                this["Map_Provider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.qrz.com/db/")]
        public string QRZ_URL_Database {
            get {
                return ((string)(this["QRZ_URL_Database"]));
            }
            set {
                this["QRZ_URL_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Log")]
        public string Log_Directory {
            get {
                return ((string)(this["Log_Directory"]));
            }
            set {
                this["Log_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database")]
        public string Database_Directory {
            get {
                return ((string)(this["Database_Directory"]));
            }
            set {
                this["Database_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Tmp")]
        public string Tmp_Directory {
            get {
                return ((string)(this["Tmp_Directory"]));
            }
            set {
                this["Tmp_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Export")]
        public string Export_Directory {
            get {
                return ((string)(this["Export_Directory"]));
            }
            set {
                this["Export_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/ScoutBase/1/StationData/")]
        public string Station_URL {
            get {
                return ((string)(this["Station_URL"]));
            }
            set {
                this["Station_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://xmldata.qrz.com/xml/current/?username=dl2alf;password=271192;agent=AirSco" +
            "ut")]
        public string QRZ_URL_Login {
            get {
                return ((string)(this["QRZ_URL_Login"]));
            }
            set {
                this["QRZ_URL_Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xmldata.qrz.com/xml/current/")]
        public string QRZ_URL_XMLData {
            get {
                return ((string)(this["QRZ_URL_XMLData"]));
            }
            set {
                this["QRZ_URL_XMLData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.airscout.eu")]
        public string SFTP_URL {
            get {
                return ((string)(this["SFTP_URL"]));
            }
            set {
                this["SFTP_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u45565180-airscout")]
        public string SFTP_User {
            get {
                return ((string)(this["SFTP_User"]));
            }
            set {
                this["SFTP_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airscout")]
        public string SFTP_Password {
            get {
                return ((string)(this["SFTP_Password"]));
            }
            set {
                this["SFTP_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.flightradar24.com/_json/airlines.php")]
        public string Airlines_Update_URL {
            get {
                return ((string)(this["Airlines_Update_URL"]));
            }
            set {
                this["Airlines_Update_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.flightradar24.com/_json/airports2.php")]
        public string Airports_Update_URL {
            get {
                return ((string)(this["Airports_Update_URL"]));
            }
            set {
                this["Airports_Update_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://data.flightradar24.com/zones/fcgi/feed.js?faa=1&mlat=1&flarm=0&adsb=1&gnd" +
            "=0&air=1&vehicles=0&estimated=0&maxage=0&gliders=0&stats=1")]
        public string Aircrafts_BaseURL {
            get {
                return ((string)(this["Aircrafts_BaseURL"]));
            }
            set {
                this["Aircrafts_BaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\CSharp\\AirScout\\Database\\ScoutBase\\V1")]
        public string StationDatabase_Export_LocalDir {
            get {
                return ((string)(this["StationDatabase_Export_LocalDir"]));
            }
            set {
                this["StationDatabase_Export_LocalDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/wsb4556518002/downloads/ScoutBase/1/StationData")]
        public string StationDatabase_Export_RemoteDir {
            get {
                return ((string)(this["StationDatabase_Export_RemoteDir"]));
            }
            set {
                this["StationDatabase_Export_RemoteDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u45565180")]
        public string StationDatabase_Export_User {
            get {
                return ((string)(this["StationDatabase_Export_User"]));
            }
            set {
                this["StationDatabase_Export_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StationDatabase_Export_Password {
            get {
                return ((string)(this["StationDatabase_Export_Password"]));
            }
            set {
                this["StationDatabase_Export_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("home208518495.1and1-/data.host")]
        public string StationDatabase_Export_RemoteHost {
            get {
                return ((string)(this["StationDatabase_Export_RemoteHost"]));
            }
            set {
                this["StationDatabase_Export_RemoteHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\CSharp\\AirScout\\Database\\AirScout\\V1")]
        public string AircraftDatabase_Export_LocalDir {
            get {
                return ((string)(this["AircraftDatabase_Export_LocalDir"]));
            }
            set {
                this["AircraftDatabase_Export_LocalDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AircraftDatabase_Export_Password {
            get {
                return ((string)(this["AircraftDatabase_Export_Password"]));
            }
            set {
                this["AircraftDatabase_Export_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/wsb4556518002/downloads/AirScout/1/AircraftData")]
        public string AircraftDatabase_Export_RemoteDir {
            get {
                return ((string)(this["AircraftDatabase_Export_RemoteDir"]));
            }
            set {
                this["AircraftDatabase_Export_RemoteDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("home208518495.1and1-/data.host")]
        public string AircraftDatabase_Export_RemoteHost {
            get {
                return ((string)(this["AircraftDatabase_Export_RemoteHost"]));
            }
            set {
                this["AircraftDatabase_Export_RemoteHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u45565180")]
        public string AircraftDatabase_Export_User {
            get {
                return ((string)(this["AircraftDatabase_Export_User"]));
            }
            set {
                this["AircraftDatabase_Export_User"] = value;
            }
        }
    }
}
