//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirScout.CAT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAT_Activate {
            get {
                return ((bool)(this["CAT_Activate"]));
            }
            set {
                this["CAT_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int CAT_Update {
            get {
                return ((int)(this["CAT_Update"]));
            }
            set {
                this["CAT_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int CAT_ResponseTimeout {
            get {
                return ((int)(this["CAT_ResponseTimeout"]));
            }
            set {
                this["CAT_ResponseTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[None]")]
        public string CAT_RigType {
            get {
                return ((string)(this["CAT_RigType"]));
            }
            set {
                this["CAT_RigType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAT_PortName {
            get {
                return ((string)(this["CAT_PortName"]));
            }
            set {
                this["CAT_PortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int CAT_Baudrate {
            get {
                return ((int)(this["CAT_Baudrate"]));
            }
            set {
                this["CAT_Baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CAT_DataBits {
            get {
                return ((int)(this["CAT_DataBits"]));
            }
            set {
                this["CAT_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public global::AirScout.CAT.PARITY CAT_Parity {
            get {
                return ((global::AirScout.CAT.PARITY)(this["CAT_Parity"]));
            }
            set {
                this["CAT_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ONE")]
        public global::AirScout.CAT.STOPBITS CAT_StopBits {
            get {
                return ((global::AirScout.CAT.STOPBITS)(this["CAT_StopBits"]));
            }
            set {
                this["CAT_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOW")]
        public global::AirScout.CAT.FLOWCONTROL CAT_RTS {
            get {
                return ((global::AirScout.CAT.FLOWCONTROL)(this["CAT_RTS"]));
            }
            set {
                this["CAT_RTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOW")]
        public global::AirScout.CAT.FLOWCONTROL CAT_DTR {
            get {
                return ((global::AirScout.CAT.FLOWCONTROL)(this["CAT_DTR"]));
            }
            set {
                this["CAT_DTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CAT_Poll {
            get {
                return ((int)(this["CAT_Poll"]));
            }
            set {
                this["CAT_Poll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int CAT_Timeout {
            get {
                return ((int)(this["CAT_Timeout"]));
            }
            set {
                this["CAT_Timeout"] = value;
            }
        }
    }
}
