//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirScout.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class New : global::System.Configuration.ApplicationSettingsBase {
        
        private static New defaultInstance = ((New)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new New())));
        
        public static New Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL2ALF")]
        public string MyCall
        {
            get
            {
                return ((string)(this["MyCall"]));
            }
            set
            {
                this["MyCall"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JO50IW")]
        public string MyLoc
        {
            get
            {
                return ((string)(this["MyLoc"]));
            }
            set
            {
                this["MyLoc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GB3MHL")]
        public string DXCall
        {
            get
            {
                return ((string)(this["DXCall"]));
            }
            set
            {
                this["DXCall"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JO02PB")]
        public string DXLoc
        {
            get
            {
                return ((string)(this["DXLoc"]));
            }
            set
            {
                this["DXLoc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Band
        {
            get
            {
                return ((string)(this["Band"]));
            }
            set
            {
                this["Band"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Planes_Update
        {
            get
            {
                return ((int)(this["Planes_Update"]));
            }
            set
            {
                this["Planes_Update"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int Planes_MinAlt
        {
            get
            {
                return ((int)(this["Planes_MinAlt"]));
            }
            set
            {
                this["Planes_MinAlt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_AutoCenter
        {
            get
            {
                return ((bool)(this["Map_AutoCenter"]));
            }
            set
            {
                this["Map_AutoCenter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Planes_Draw_Path
        {
            get
            {
                return ((bool)(this["Planes_Draw_Path"]));
            }
            set
            {
                this["Planes_Draw_Path"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_GroundClearance
        {
            get
            {
                return ((double)(this["Path_GroundClearance"]));
            }
            set
            {
                this["Path_GroundClearance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12200")]
        public int Planes_MaxAlt
        {
            get
            {
                return ((int)(this["Planes_MaxAlt"]));
            }
            set
            {
                this["Planes_MaxAlt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double MyHeight
        {
            get
            {
                return ((double)(this["MyHeight"]));
            }
            set
            {
                this["MyHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double DXHeight
        {
            get
            {
                return ((double)(this["DXHeight"]));
            }
            set
            {
                this["DXHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database\\calls.txt")]
        public string Calls_FileName
        {
            get
            {
                return ((string)(this["Calls_FileName"]));
            }
            set
            {
                this["Calls_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database\\lastcalls.txt")]
        public string LastCalls_FileName
        {
            get
            {
                return ((string)(this["LastCalls_FileName"]));
            }
            set
            {
                this["LastCalls_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database\\call3.txt")]
        public string WSJTCalls_FileName
        {
            get
            {
                return ((string)(this["WSJTCalls_FileName"]));
            }
            set
            {
                this["WSJTCalls_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>DL2ALF</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LastCalls
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastCalls"]));
            }
            set
            {
                this["LastCalls"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database\\Aircrafts.txt")]
        public string AircraftTypes_FileName
        {
            get
            {
                return ((string)(this["AircraftTypes_FileName"]));
            }
            set
            {
                this["AircraftTypes_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.flugzeuginfo.net/table_accodes_en.php")]
        public string AircraftTypes_URL
        {
            get
            {
                return ((string)(this["AircraftTypes_URL"]));
            }
            set
            {
                this["AircraftTypes_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int LastCalls_MaxCount
        {
            get
            {
                return ((int)(this["LastCalls_MaxCount"]));
            }
            set
            {
                this["LastCalls_MaxCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\GLOBE")]
        public string Elevation_GLOBE_DataPath
        {
            get
            {
                return ((string)(this["Elevation_GLOBE_DataPath"]));
            }
            set
            {
                this["Elevation_GLOBE_DataPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>50M</string>
  <string>70M</string>
  <string>144M</string>
  <string>432M</string>
  <string>1.2G</string>
  <string>2.3G</string>
  <string>3.4G</string>
  <string>5.7G</string>
  <string>10G</string>
  <string>24G</string>
  <string>47G</string>
  <string>76G</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Band_Settings
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["Band_Settings"]));
            }
            set
            {
                this["Band_Settings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Planes_Filter_Min_Alt
        {
            get
            {
                return ((string)(this["Planes_Filter_Min_Alt"]));
            }
            set
            {
                this["Planes_Filter_Min_Alt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Planes_Filter_Min_Cat
        {
            get
            {
                return ((string)(this["Planes_Filter_Min_Cat"]));
            }
            set
            {
                this["Planes_Filter_Min_Cat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public int General_ShowISSPath
        {
            get
            {
                return ((int)(this["General_ShowISSPath"]));
            }
            set
            {
                this["General_ShowISSPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public double MinLon
        {
            get
            {
                return ((double)(this["MinLon"]));
            }
            set
            {
                this["MinLon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxLon
        {
            get
            {
                return ((double)(this["MaxLon"]));
            }
            set
            {
                this["MaxLon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double MinLat
        {
            get
            {
                return ((double)(this["MinLat"]));
            }
            set
            {
                this["MinLat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double MaxLat
        {
            get
            {
                return ((double)(this["MaxLat"]));
            }
            set
            {
                this["MaxLat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.937067")]
        public double MyLat
        {
            get
            {
                return ((double)(this["MyLat"]));
            }
            set
            {
                this["MyLat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.68327")]
        public double MyLon
        {
            get
            {
                return ((double)(this["MyLon"]));
            }
            set
            {
                this["MyLon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.05626084")]
        public double DXLat
        {
            get
            {
                return ((double)(this["DXLat"]));
            }
            set
            {
                this["DXLat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.28022909")]
        public double DXLon
        {
            get
            {
                return ((double)(this["DXLon"]));
            }
            set
            {
                this["DXLon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public double DXElevation
        {
            get
            {
                return ((double)(this["DXElevation"]));
            }
            set
            {
                this["DXElevation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("328")]
        public double MyElevation
        {
            get
            {
                return ((double)(this["MyElevation"]));
            }
            set
            {
                this["MyElevation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM3")]
        public string Elevation_SRTM3_DataPath
        {
            get
            {
                return ((string)(this["Elevation_SRTM3_DataPath"]));
            }
            set
            {
                this["Elevation_SRTM3_DataPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM1")]
        public string Elevation_SRTM1_DataPath
        {
            get
            {
                return ((string)(this["Elevation_SRTM1_DataPath"]));
            }
            set
            {
                this["Elevation_SRTM1_DataPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM3_Enabled
        {
            get
            {
                return ((bool)(this["Elevation_SRTM3_Enabled"]));
            }
            set
            {
                this["Elevation_SRTM3_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM1_Enabled
        {
            get
            {
                return ((bool)(this["Elevation_SRTM1_Enabled"]));
            }
            set
            {
                this["Elevation_SRTM1_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.qrz.com/db/")]
        public string QRZ_URL_Database
        {
            get
            {
                return ((string)(this["QRZ_URL_Database"]));
            }
            set
            {
                this["QRZ_URL_Database"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Path_NearFieldSuppression
        {
            get
            {
                return ((double)(this["Path_NearFieldSuppression"]));
            }
            set
            {
                this["Path_NearFieldSuppression"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double Path_StepWidth
        {
            get
            {
                return ((double)(this["Path_StepWidth"]));
            }
            set
            {
                this["Path_StepWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/")]
        public string Elevation_SRTM3_URL
        {
            get
            {
                return ((string)(this["Elevation_SRTM3_URL"]));
            }
            set
            {
                this["Elevation_SRTM3_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Path_History_StepWidth
        {
            get
            {
                return ((int)(this["Path_History_StepWidth"]));
            }
            set
            {
                this["Path_History_StepWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alarm_BringWindowToFront
        {
            get
            {
                return ((bool)(this["Alarm_BringWindowToFront"]));
            }
            set
            {
                this["Alarm_BringWindowToFront"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alarm_PlaySound
        {
            get
            {
                return ((bool)(this["Alarm_PlaySound"]));
            }
            set
            {
                this["Alarm_PlaySound"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Alarm_Distance
        {
            get
            {
                return ((double)(this["Alarm_Distance"]));
            }
            set
            {
                this["Alarm_Distance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Alarm_Activate
        {
            get
            {
                return ((bool)(this["Alarm_Activate"]));
            }
            set
            {
                this["Alarm_Activate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database\\localobstructions.txt")]
        public string LocalObstruction_FileName
        {
            get
            {
                return ((string)(this["LocalObstruction_FileName"]));
            }
            set
            {
                this["LocalObstruction_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Path_Cubic_Spline
        {
            get
            {
                return ((bool)(this["Path_Cubic_Spline"]));
            }
            set
            {
                this["Path_Cubic_Spline"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Horizon_Plot_Cartesian
        {
            get
            {
                return ((bool)(this["Horizon_Plot_Cartesian"]));
            }
            set
            {
                this["Horizon_Plot_Cartesian"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Horizon_Plot_Polar
        {
            get
            {
                return ((bool)(this["Horizon_Plot_Polar"]));
            }
            set
            {
                this["Horizon_Plot_Polar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9871")]
        public int WinTest_Port
        {
            get
            {
                return ((int)(this["WinTest_Port"]));
            }
            set
            {
                this["WinTest_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9872")]
        public int Server_Port
        {
            get
            {
                return ((int)(this["Server_Port"]));
            }
            set
            {
                this["Server_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Path_BestCaseElevation
        {
            get
            {
                return ((bool)(this["Path_BestCaseElevation"]));
            }
            set
            {
                this["Path_BestCaseElevation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Icon")]
        public string Planes_IconPath
        {
            get
            {
                return ((string)(this["Planes_IconPath"]));
            }
            set
            {
                this["Planes_IconPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("plane.png")]
        public string Planes_IconFileName
        {
            get
            {
                return ((string)(this["Planes_IconFileName"]));
            }
            set
            {
                this["Planes_IconFileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string Planes_PlaneFeed2
        {
            get
            {
                return ((string)(this["Planes_PlaneFeed2"]));
            }
            set
            {
                this["Planes_PlaneFeed2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string Planes_PlaneFeed3
        {
            get
            {
                return ((string)(this["Planes_PlaneFeed3"]));
            }
            set
            {
                this["Planes_PlaneFeed3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string Planes_PlaneFeed1
        {
            get
            {
                return ((string)(this["Planes_PlaneFeed1"]));
            }
            set
            {
                this["Planes_PlaneFeed1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_BandSettings
        {
            get
            {
                return ((string)(this["Path_BandSettings"]));
            }
            set
            {
                this["Path_BandSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Planes_Position_TTL
        {
            get
            {
                return ((int)(this["Planes_Position_TTL"]));
            }
            set
            {
                this["Planes_Position_TTL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Server_Activate
        {
            get
            {
                return ((bool)(this["Server_Activate"]));
            }
            set
            {
                this["Server_Activate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AS")]
        public string Server_Name
        {
            get
            {
                return ((string)(this["Server_Name"]));
            }
            set
            {
                this["Server_Name"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Africa/
http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Australia/
http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/
http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Islands/
http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/North_America/
http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/South_America/")]
        public string Elevation_SRTM3_URLs
        {
            get
            {
                return ((string)(this["Elevation_SRTM3_URLs"]));
            }
            set
            {
                this["Elevation_SRTM3_URLs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenStreetMap")]
        public string Map_Provider
        {
            get
            {
                return ((string)(this["Map_Provider"]));
            }
            set
            {
                this["Map_Provider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Map_Provider_Accepted
        {
            get
            {
                return ((string)(this["Map_Provider_Accepted"]));
            }
            set
            {
                this["Map_Provider_Accepted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif; 11;Bold")]
        public string Map_ToolTipFont
        {
            get
            {
                return ((string)(this["Map_ToolTipFont"]));
            }
            set
            {
                this["Map_ToolTipFont"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.33")]
        public double Path_Default_K_Factor
        {
            get
            {
                return ((double)(this["Path_Default_K_Factor"]));
            }
            set
            {
                this["Path_Default_K_Factor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double Path_Default_F1_Clearance
        {
            get
            {
                return ((double)(this["Path_Default_F1_Clearance"]));
            }
            set
            {
                this["Path_Default_F1_Clearance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Ground_Clearance
        {
            get
            {
                return ((double)(this["Path_Default_Ground_Clearance"]));
            }
            set
            {
                this["Path_Default_Ground_Clearance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Path_Default_Max_Distance
        {
            get
            {
                return ((double)(this["Path_Default_Max_Distance"]));
            }
            set
            {
                this["Path_Default_Max_Distance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Max_Squint
        {
            get
            {
                return ((double)(this["Path_Default_Max_Squint"]));
            }
            set
            {
                this["Path_Default_Max_Squint"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Max_Elevation
        {
            get
            {
                return ((double)(this["Path_Default_Max_Elevation"]));
            }
            set
            {
                this["Path_Default_Max_Elevation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/")]
        public string SpecLab_URL
        {
            get
            {
                return ((string)(this["SpecLab_URL"]));
            }
            set
            {
                this["SpecLab_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SpecLab_Update
        {
            get
            {
                return ((double)(this["SpecLab_Update"]));
            }
            set
            {
                this["SpecLab_Update"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_fft_expt.json")]
        public string SpecLab_FileName
        {
            get
            {
                return ((string)(this["SpecLab_FileName"]));
            }
            set
            {
                this["SpecLab_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int SpecLab_F1
        {
            get
            {
                return ((int)(this["SpecLab_F1"]));
            }
            set
            {
                this["SpecLab_F1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int SpecLab_F2
        {
            get
            {
                return ((int)(this["SpecLab_F2"]));
            }
            set
            {
                this["SpecLab_F2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpecLab_Enabled
        {
            get
            {
                return ((bool)(this["SpecLab_Enabled"]));
            }
            set
            {
                this["SpecLab_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Metric
        {
            get
            {
                return ((bool)(this["InfoWin_Metric"]));
            }
            set
            {
                this["InfoWin_Metric"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Imperial
        {
            get
            {
                return ((bool)(this["InfoWin_Imperial"]));
            }
            set
            {
                this["InfoWin_Imperial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Position
        {
            get
            {
                return ((bool)(this["InfoWin_Position"]));
            }
            set
            {
                this["InfoWin_Position"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Time
        {
            get
            {
                return ((bool)(this["InfoWin_Time"]));
            }
            set
            {
                this["InfoWin_Time"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Epsilon
        {
            get
            {
                return ((bool)(this["InfoWin_Epsilon"]));
            }
            set
            {
                this["InfoWin_Epsilon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Squint
        {
            get
            {
                return ((bool)(this["InfoWin_Squint"]));
            }
            set
            {
                this["InfoWin_Squint"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Track
        {
            get
            {
                return ((bool)(this["InfoWin_Track"]));
            }
            set
            {
                this["InfoWin_Track"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Type
        {
            get
            {
                return ((bool)(this["InfoWin_Type"]));
            }
            set
            {
                this["InfoWin_Type"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Alt
        {
            get
            {
                return ((bool)(this["InfoWin_Alt"]));
            }
            set
            {
                this["InfoWin_Alt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Dist
        {
            get
            {
                return ((bool)(this["InfoWin_Dist"]));
            }
            set
            {
                this["InfoWin_Dist"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Speed
        {
            get
            {
                return ((bool)(this["InfoWin_Speed"]));
            }
            set
            {
                this["InfoWin_Speed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Angle
        {
            get
            {
                return ((bool)(this["InfoWin_Angle"]));
            }
            set
            {
                this["InfoWin_Angle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SFTP_Enabled
        {
            get
            {
                return ((bool)(this["SFTP_Enabled"]));
            }
            set
            {
                this["SFTP_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/airscout.pwd")]
        public string SFTP_PwdURL
        {
            get
            {
                return ((string)(this["SFTP_PwdURL"]));
            }
            set
            {
                this["SFTP_PwdURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Agree
        {
            get
            {
                return ((bool)(this["First_Agree"]));
            }
            set
            {
                this["First_Agree"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Disagree
        {
            get
            {
                return ((bool)(this["First_Disagree"]));
            }
            set
            {
                this["First_Disagree"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Privacy
        {
            get
            {
                return ((bool)(this["First_Privacy"]));
            }
            set
            {
                this["First_Privacy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun
        {
            get
            {
                return ((bool)(this["FirstRun"]));
            }
            set
            {
                this["FirstRun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowZoomBox
        {
            get
            {
                return ((bool)(this["Map_ShowZoomBox"]));
            }
            set
            {
                this["Map_ShowZoomBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowFilterBox
        {
            get
            {
                return ((bool)(this["Map_ShowFilterBox"]));
            }
            set
            {
                this["Map_ShowFilterBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowAlarmBox
        {
            get
            {
                return ((bool)(this["Map_ShowAlarmBox"]));
            }
            set
            {
                this["Map_ShowAlarmBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowInfoBox
        {
            get
            {
                return ((bool)(this["Map_ShowInfoBox"]));
            }
            set
            {
                this["Map_ShowInfoBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainSplitter_Distance
        {
            get
            {
                return ((int)(this["MainSplitter_Distance"]));
            }
            set
            {
                this["MainSplitter_Distance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MapSplitter_Distance
        {
            get
            {
                return ((int)(this["MapSplitter_Distance"]));
            }
            set
            {
                this["MapSplitter_Distance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Activate
        {
            get
            {
                return ((bool)(this["Track_Activate"]));
            }
            set
            {
                this["Track_Activate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>[Network] AirScout</string>
  <string>[Network] Win-Test</string>
  <string>[DDE] Ham Radio Deluxe</string>
  <string>[DDE] Nova</string>
  <string>[Serial] Yaesu GS-232A (Az only)</string>
  <string>[Serial] Yaesu GS-232A (Az/El)</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Track_Protocol
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["Track_Protocol"]));
            }
            set
            {
                this["Track_Protocol"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Track_SetAz
        {
            get
            {
                return ((double)(this["Track_SetAz"]));
            }
            set
            {
                this["Track_SetAz"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Track_SetEl
        {
            get
            {
                return ((double)(this["Track_SetEl"]));
            }
            set
            {
                this["Track_SetEl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Planes_IconSize_L
        {
            get
            {
                return ((int)(this["Planes_IconSize_L"]));
            }
            set
            {
                this["Planes_IconSize_L"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Planes_IconSize_M
        {
            get
            {
                return ((int)(this["Planes_IconSize_M"]));
            }
            set
            {
                this["Planes_IconSize_M"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int Planes_IconSize_H
        {
            get
            {
                return ((int)(this["Planes_IconSize_H"]));
            }
            set
            {
                this["Planes_IconSize_H"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int Planes_IconSize_S
        {
            get
            {
                return ((int)(this["Planes_IconSize_S"]));
            }
            set
            {
                this["Planes_IconSize_S"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9880")]
        public int Webserver_Port
        {
            get
            {
                return ((int)(this["Webserver_Port"]));
            }
            set
            {
                this["Webserver_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/31/2015 15:21:00")]
        public global::System.DateTime News_LastUpdate
        {
            get
            {
                return ((global::System.DateTime)(this["News_LastUpdate"]));
            }
            set
            {
                this["News_LastUpdate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int News_Interval
        {
            get
            {
                return ((int)(this["News_Interval"]));
            }
            set
            {
                this["News_Interval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/news.html")]
        public global::System.Uri News_URL
        {
            get
            {
                return ((global::System.Uri)(this["News_URL"]));
            }
            set
            {
                this["News_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_UDP_WinTest
        {
            get
            {
                return ((bool)(this["Track_UDP_WinTest"]));
            }
            set
            {
                this["Track_UDP_WinTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_DDE_HRD
        {
            get
            {
                return ((bool)(this["Track_DDE_HRD"]));
            }
            set
            {
                this["Track_DDE_HRD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM13")]
        public string Track_Serial_Port
        {
            get
            {
                return ((string)(this["Track_Serial_Port"]));
            }
            set
            {
                this["Track_Serial_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int Track_Serial_Baudrate
        {
            get
            {
                return ((int)(this["Track_Serial_Baudrate"]));
            }
            set
            {
                this["Track_Serial_Baudrate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Serial_GS232_AZ
        {
            get
            {
                return ((bool)(this["Track_Serial_GS232_AZ"]));
            }
            set
            {
                this["Track_Serial_GS232_AZ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_File_WSJT
        {
            get
            {
                return ((bool)(this["Track_File_WSJT"]));
            }
            set
            {
                this["Track_File_WSJT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_File_Native
        {
            get
            {
                return ((bool)(this["Track_File_Native"]));
            }
            set
            {
                this["Track_File_Native"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Serial_GS232_AZEL
        {
            get
            {
                return ((bool)(this["Track_Serial_GS232_AZEL"]));
            }
            set
            {
                this["Track_Serial_GS232_AZEL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_UDP_AirScout
        {
            get
            {
                return ((bool)(this["Track_UDP_AirScout"]));
            }
            set
            {
                this["Track_UDP_AirScout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_Serial_None
        {
            get
            {
                return ((bool)(this["Track_Serial_None"]));
            }
            set
            {
                this["Track_Serial_None"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_UDP_None
        {
            get
            {
                return ((bool)(this["Track_UDP_None"]));
            }
            set
            {
                this["Track_UDP_None"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_DDE_None
        {
            get
            {
                return ((bool)(this["Track_DDE_None"]));
            }
            set
            {
                this["Track_DDE_None"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_File_None
        {
            get
            {
                return ((bool)(this["Track_File_None"]));
            }
            set
            {
                this["Track_File_None"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9871")]
        public int Track_UDP_WinTest_Port
        {
            get
            {
                return ((int)(this["Track_UDP_WinTest_Port"]));
            }
            set
            {
                this["Track_UDP_WinTest_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9872")]
        public int Track_UDP_AirScout_Port
        {
            get
            {
                return ((int)(this["Track_UDP_AirScout_Port"]));
            }
            set
            {
                this["Track_UDP_AirScout_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/donate.html")]
        public string Donate_URL
        {
            get
            {
                return ((string)(this["Donate_URL"]));
            }
            set
            {
                this["Donate_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Planes_Filter_Max_Circumcircle
        {
            get
            {
                return ((string)(this["Planes_Filter_Max_Circumcircle"]));
            }
            set
            {
                this["Planes_Filter_Max_Circumcircle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ngdc.noaa.gov/mgg/topo/DATATILES/elev/")]
        public string Elevation_GLOBE_URL
        {
            get
            {
                return ((string)(this["Elevation_GLOBE_URL"]));
            }
            set
            {
                this["Elevation_GLOBE_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ngdc.noaa.gov/mgg/topo/DATATILES/elev/\r\nhttp://www.airscout.eu/downloa" +
            "ds/GLOBE")]
        public string Elevation_GLOBE_URLs
        {
            get
            {
                return ((string)(this["Elevation_GLOBE_URLs"]));
            }
            set
            {
                this["Elevation_GLOBE_URLs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Time_Mode_Online
        {
            get
            {
                return ((bool)(this["Time_Mode_Online"]));
            }
            set
            {
                this["Time_Mode_Online"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-02-25")]
        public global::System.DateTime Time_Offline
        {
            get
            {
                return ((global::System.DateTime)(this["Time_Offline"]));
            }
            set
            {
                this["Time_Offline"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airport.png")]
        public string Airports_IconFileName
        {
            get
            {
                return ((string)(this["Airports_IconFileName"]));
            }
            set
            {
                this["Airports_IconFileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Airports_Activate
        {
            get
            {
                return ((bool)(this["Airports_Activate"]));
            }
            set
            {
                this["Airports_Activate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database\\Airlines.txt")]
        public string Database_Airlines_FileName
        {
            get
            {
                return ((string)(this["Database_Airlines_FileName"]));
            }
            set
            {
                this["Database_Airlines_FileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.flugzeuginfo.net/table_airlinecodes_airline_en.php")]
        public string Database_Airlines_URL
        {
            get
            {
                return ((string)(this["Database_Airlines_URL"]));
            }
            set
            {
                this["Database_Airlines_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Map_Update
        {
            get
            {
                return ((int)(this["Map_Update"]));
            }
            set
            {
                this["Map_Update"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_GLOBE_Enabled
        {
            get
            {
                return ((bool)(this["Elevation_GLOBE_Enabled"]));
            }
            set
            {
                this["Elevation_GLOBE_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/database/")]
        public string Database_Update_URL
        {
            get
            {
                return ((string)(this["Database_Update_URL"]));
            }
            set
            {
                this["Database_Update_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Database_Update_Enabled
        {
            get
            {
                return ((bool)(this["Database_Update_Enabled"]));
            }
            set
            {
                this["Database_Update_Enabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.Forms.FormWindowState General_WindowState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["General_WindowState"]));
            }
            set
            {
                this["General_WindowState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size General_WindowSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["General_WindowSize"]));
            }
            set
            {
                this["General_WindowSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point General_WindowLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["General_WindowLocation"]));
            }
            set
            {
                this["General_WindowLocation"] = value;
            }
        }
    }
}
