//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirScout.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL2ALF")]
        public string MyCall {
            get {
                return ((string)(this["MyCall"]));
            }
            set {
                this["MyCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GB3MHZ")]
        public string DXCall {
            get {
                return ((string)(this["DXCall"]));
            }
            set {
                this["DXCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B1_2G")]
        public global::ScoutBase.Core.BAND Band {
            get {
                return ((global::ScoutBase.Core.BAND)(this["Band"]));
            }
            set {
                this["Band"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Planes_Update {
            get {
                return ((int)(this["Planes_Update"]));
            }
            set {
                this["Planes_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int Planes_MinAlt {
            get {
                return ((int)(this["Planes_MinAlt"]));
            }
            set {
                this["Planes_MinAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_AutoCenter {
            get {
                return ((bool)(this["Map_AutoCenter"]));
            }
            set {
                this["Map_AutoCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Planes_Draw_Path {
            get {
                return ((bool)(this["Planes_Draw_Path"]));
            }
            set {
                this["Planes_Draw_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_GroundClearance {
            get {
                return ((double)(this["Path_GroundClearance"]));
            }
            set {
                this["Path_GroundClearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12200")]
        public int Planes_MaxAlt {
            get {
                return ((int)(this["Planes_MaxAlt"]));
            }
            set {
                this["Planes_MaxAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double MyHeight {
            get {
                return ((double)(this["MyHeight"]));
            }
            set {
                this["MyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double DXHeight {
            get {
                return ((double)(this["DXHeight"]));
            }
            set {
                this["DXHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Watchlist_MaxCount {
            get {
                return ((int)(this["Watchlist_MaxCount"]));
            }
            set {
                this["Watchlist_MaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Planes_Filter_Min_Alt {
            get {
                return ((int)(this["Planes_Filter_Min_Alt"]));
            }
            set {
                this["Planes_Filter_Min_Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public global::AirScout.Core.PLANECATEGORY Planes_Filter_Min_Category {
            get {
                return ((global::AirScout.Core.PLANECATEGORY)(this["Planes_Filter_Min_Category"]));
            }
            set {
                this["Planes_Filter_Min_Category"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public double MinLon {
            get {
                return ((double)(this["MinLon"]));
            }
            set {
                this["MinLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxLon {
            get {
                return ((double)(this["MaxLon"]));
            }
            set {
                this["MaxLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double MinLat {
            get {
                return ((double)(this["MinLat"]));
            }
            set {
                this["MinLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double MaxLat {
            get {
                return ((double)(this["MaxLat"]));
            }
            set {
                this["MaxLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.937067")]
        public double MyLat {
            get {
                return ((double)(this["MyLat"]));
            }
            set {
                this["MyLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.68327")]
        public double MyLon {
            get {
                return ((double)(this["MyLon"]));
            }
            set {
                this["MyLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.05626084")]
        public double DXLat {
            get {
                return ((double)(this["DXLat"]));
            }
            set {
                this["DXLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.28022909")]
        public double DXLon {
            get {
                return ((double)(this["DXLon"]));
            }
            set {
                this["DXLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public double DXElevation {
            get {
                return ((double)(this["DXElevation"]));
            }
            set {
                this["DXElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("328")]
        public double MyElevation {
            get {
                return ((double)(this["MyElevation"]));
            }
            set {
                this["MyElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM3_Enabled {
            get {
                return ((bool)(this["Elevation_SRTM3_Enabled"]));
            }
            set {
                this["Elevation_SRTM3_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM1_Enabled {
            get {
                return ((bool)(this["Elevation_SRTM1_Enabled"]));
            }
            set {
                this["Elevation_SRTM1_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.qrz.com/db/")]
        public string QRZ_URL_Database {
            get {
                return ((string)(this["QRZ_URL_Database"]));
            }
            set {
                this["QRZ_URL_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Path_NearFieldSuppression {
            get {
                return ((double)(this["Path_NearFieldSuppression"]));
            }
            set {
                this["Path_NearFieldSuppression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Path_History_StepWidth {
            get {
                return ((int)(this["Path_History_StepWidth"]));
            }
            set {
                this["Path_History_StepWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alarm_BringWindowToFront {
            get {
                return ((bool)(this["Alarm_BringWindowToFront"]));
            }
            set {
                this["Alarm_BringWindowToFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alarm_PlaySound {
            get {
                return ((bool)(this["Alarm_PlaySound"]));
            }
            set {
                this["Alarm_PlaySound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Alarm_Distance {
            get {
                return ((double)(this["Alarm_Distance"]));
            }
            set {
                this["Alarm_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Alarm_Activate {
            get {
                return ((bool)(this["Alarm_Activate"]));
            }
            set {
                this["Alarm_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Path_Cubic_Spline {
            get {
                return ((bool)(this["Path_Cubic_Spline"]));
            }
            set {
                this["Path_Cubic_Spline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Horizon_Plot_Cartesian {
            get {
                return ((bool)(this["Horizon_Plot_Cartesian"]));
            }
            set {
                this["Horizon_Plot_Cartesian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Horizon_Plot_Polar {
            get {
                return ((bool)(this["Horizon_Plot_Polar"]));
            }
            set {
                this["Horizon_Plot_Polar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9871")]
        public int WinTest_Port {
            get {
                return ((int)(this["WinTest_Port"]));
            }
            set {
                this["WinTest_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9872")]
        public int Server_Port {
            get {
                return ((int)(this["Server_Port"]));
            }
            set {
                this["Server_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Path_BestCaseElevation {
            get {
                return ((bool)(this["Path_BestCaseElevation"]));
            }
            set {
                this["Path_BestCaseElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Icon")]
        public string Icon_Directory {
            get {
                return ((string)(this["Icon_Directory"]));
            }
            set {
                this["Icon_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("plane.png")]
        public string Planes_IconFileName {
            get {
                return ((string)(this["Planes_IconFileName"]));
            }
            set {
                this["Planes_IconFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string Planes_PlaneFeed2 {
            get {
                return ((string)(this["Planes_PlaneFeed2"]));
            }
            set {
                this["Planes_PlaneFeed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string Planes_PlaneFeed3 {
            get {
                return ((string)(this["Planes_PlaneFeed3"]));
            }
            set {
                this["Planes_PlaneFeed3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           Virtual Radar Server")]
        public string Planes_PlaneFeed1 {
            get {
                return ((string)(this["Planes_PlaneFeed1"]));
            }
            set {
                this["Planes_PlaneFeed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Planes_Position_TTL {
            get {
                return ((int)(this["Planes_Position_TTL"]));
            }
            set {
                this["Planes_Position_TTL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Server_Activate {
            get {
                return ((bool)(this["Server_Activate"]));
            }
            set {
                this["Server_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AS")]
        public string Server_Name {
            get {
                return ((string)(this["Server_Name"]));
            }
            set {
                this["Server_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenStreetMap")]
        public string Map_Provider {
            get {
                return ((string)(this["Map_Provider"]));
            }
            set {
                this["Map_Provider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Map_Provider_Accepted {
            get {
                return ((string)(this["Map_Provider_Accepted"]));
            }
            set {
                this["Map_Provider_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif; 11;Bold")]
        public string Map_ToolTipFont {
            get {
                return ((string)(this["Map_ToolTipFont"]));
            }
            set {
                this["Map_ToolTipFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10080/")]
        public string SpecLab_URL {
            get {
                return ((string)(this["SpecLab_URL"]));
            }
            set {
                this["SpecLab_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SpecLab_Update {
            get {
                return ((double)(this["SpecLab_Update"]));
            }
            set {
                this["SpecLab_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_fft_expt.json")]
        public string SpecLab_FileName {
            get {
                return ((string)(this["SpecLab_FileName"]));
            }
            set {
                this["SpecLab_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int SpecLab_F1 {
            get {
                return ((int)(this["SpecLab_F1"]));
            }
            set {
                this["SpecLab_F1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int SpecLab_F2 {
            get {
                return ((int)(this["SpecLab_F2"]));
            }
            set {
                this["SpecLab_F2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpecLab_Enabled {
            get {
                return ((bool)(this["SpecLab_Enabled"]));
            }
            set {
                this["SpecLab_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Metric {
            get {
                return ((bool)(this["InfoWin_Metric"]));
            }
            set {
                this["InfoWin_Metric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Imperial {
            get {
                return ((bool)(this["InfoWin_Imperial"]));
            }
            set {
                this["InfoWin_Imperial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Position {
            get {
                return ((bool)(this["InfoWin_Position"]));
            }
            set {
                this["InfoWin_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Time {
            get {
                return ((bool)(this["InfoWin_Time"]));
            }
            set {
                this["InfoWin_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Epsilon {
            get {
                return ((bool)(this["InfoWin_Epsilon"]));
            }
            set {
                this["InfoWin_Epsilon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Squint {
            get {
                return ((bool)(this["InfoWin_Squint"]));
            }
            set {
                this["InfoWin_Squint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Track {
            get {
                return ((bool)(this["InfoWin_Track"]));
            }
            set {
                this["InfoWin_Track"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Type {
            get {
                return ((bool)(this["InfoWin_Type"]));
            }
            set {
                this["InfoWin_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Alt {
            get {
                return ((bool)(this["InfoWin_Alt"]));
            }
            set {
                this["InfoWin_Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWin_Dist {
            get {
                return ((bool)(this["InfoWin_Dist"]));
            }
            set {
                this["InfoWin_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Speed {
            get {
                return ((bool)(this["InfoWin_Speed"]));
            }
            set {
                this["InfoWin_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWin_Angle {
            get {
                return ((bool)(this["InfoWin_Angle"]));
            }
            set {
                this["InfoWin_Angle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Agree {
            get {
                return ((bool)(this["First_Agree"]));
            }
            set {
                this["First_Agree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Disagree {
            get {
                return ((bool)(this["First_Disagree"]));
            }
            set {
                this["First_Disagree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool First_Privacy {
            get {
                return ((bool)(this["First_Privacy"]));
            }
            set {
                this["First_Privacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowZoomBox {
            get {
                return ((bool)(this["Map_ShowZoomBox"]));
            }
            set {
                this["Map_ShowZoomBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowFilterBox {
            get {
                return ((bool)(this["Map_ShowFilterBox"]));
            }
            set {
                this["Map_ShowFilterBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowAlarmBox {
            get {
                return ((bool)(this["Map_ShowAlarmBox"]));
            }
            set {
                this["Map_ShowAlarmBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_ShowInfoBox {
            get {
                return ((bool)(this["Map_ShowInfoBox"]));
            }
            set {
                this["Map_ShowInfoBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainSplitter_Distance {
            get {
                return ((int)(this["MainSplitter_Distance"]));
            }
            set {
                this["MainSplitter_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MapSplitter_Distance {
            get {
                return ((int)(this["MapSplitter_Distance"]));
            }
            set {
                this["MapSplitter_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Activate {
            get {
                return ((bool)(this["Track_Activate"]));
            }
            set {
                this["Track_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Track_SetAz {
            get {
                return ((double)(this["Track_SetAz"]));
            }
            set {
                this["Track_SetAz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Track_SetEl {
            get {
                return ((double)(this["Track_SetEl"]));
            }
            set {
                this["Track_SetEl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Planes_IconSize_L {
            get {
                return ((int)(this["Planes_IconSize_L"]));
            }
            set {
                this["Planes_IconSize_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Planes_IconSize_M {
            get {
                return ((int)(this["Planes_IconSize_M"]));
            }
            set {
                this["Planes_IconSize_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int Planes_IconSize_H {
            get {
                return ((int)(this["Planes_IconSize_H"]));
            }
            set {
                this["Planes_IconSize_H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int Planes_IconSize_S {
            get {
                return ((int)(this["Planes_IconSize_S"]));
            }
            set {
                this["Planes_IconSize_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9880")]
        public int Webserver_Port {
            get {
                return ((int)(this["Webserver_Port"]));
            }
            set {
                this["Webserver_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/31/2015 15:21:00")]
        public global::System.DateTime News_LastUpdate {
            get {
                return ((global::System.DateTime)(this["News_LastUpdate"]));
            }
            set {
                this["News_LastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int News_Interval {
            get {
                return ((int)(this["News_Interval"]));
            }
            set {
                this["News_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/news.html")]
        public global::System.Uri News_URL {
            get {
                return ((global::System.Uri)(this["News_URL"]));
            }
            set {
                this["News_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_UDP_WinTest {
            get {
                return ((bool)(this["Track_UDP_WinTest"]));
            }
            set {
                this["Track_UDP_WinTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_DDE_HRD {
            get {
                return ((bool)(this["Track_DDE_HRD"]));
            }
            set {
                this["Track_DDE_HRD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM13")]
        public string Track_Serial_Port {
            get {
                return ((string)(this["Track_Serial_Port"]));
            }
            set {
                this["Track_Serial_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int Track_Serial_Baudrate {
            get {
                return ((int)(this["Track_Serial_Baudrate"]));
            }
            set {
                this["Track_Serial_Baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Serial_GS232_AZ {
            get {
                return ((bool)(this["Track_Serial_GS232_AZ"]));
            }
            set {
                this["Track_Serial_GS232_AZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_File_WSJT {
            get {
                return ((bool)(this["Track_File_WSJT"]));
            }
            set {
                this["Track_File_WSJT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_File_Native {
            get {
                return ((bool)(this["Track_File_Native"]));
            }
            set {
                this["Track_File_Native"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_Serial_GS232_AZEL {
            get {
                return ((bool)(this["Track_Serial_GS232_AZEL"]));
            }
            set {
                this["Track_Serial_GS232_AZEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Track_UDP_AirScout {
            get {
                return ((bool)(this["Track_UDP_AirScout"]));
            }
            set {
                this["Track_UDP_AirScout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_Serial_None {
            get {
                return ((bool)(this["Track_Serial_None"]));
            }
            set {
                this["Track_Serial_None"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_UDP_None {
            get {
                return ((bool)(this["Track_UDP_None"]));
            }
            set {
                this["Track_UDP_None"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_DDE_None {
            get {
                return ((bool)(this["Track_DDE_None"]));
            }
            set {
                this["Track_DDE_None"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Track_File_None {
            get {
                return ((bool)(this["Track_File_None"]));
            }
            set {
                this["Track_File_None"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9871")]
        public int Track_UDP_WinTest_Port {
            get {
                return ((int)(this["Track_UDP_WinTest_Port"]));
            }
            set {
                this["Track_UDP_WinTest_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9872")]
        public int Track_UDP_AirScout_Port {
            get {
                return ((int)(this["Track_UDP_AirScout_Port"]));
            }
            set {
                this["Track_UDP_AirScout_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/donate.html")]
        public string Donate_URL {
            get {
                return ((string)(this["Donate_URL"]));
            }
            set {
                this["Donate_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Planes_Filter_Max_Circumcircle {
            get {
                return ((int)(this["Planes_Filter_Max_Circumcircle"]));
            }
            set {
                this["Planes_Filter_Max_Circumcircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Time_Mode_Online {
            get {
                return ((bool)(this["Time_Mode_Online"]));
            }
            set {
                this["Time_Mode_Online"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-02-25")]
        public global::System.DateTime Time_Offline {
            get {
                return ((global::System.DateTime)(this["Time_Offline"]));
            }
            set {
                this["Time_Offline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airport.png")]
        public string Airports_IconFileName {
            get {
                return ((string)(this["Airports_IconFileName"]));
            }
            set {
                this["Airports_IconFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Airports_Activate {
            get {
                return ((bool)(this["Airports_Activate"]));
            }
            set {
                this["Airports_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Map_Update {
            get {
                return ((int)(this["Map_Update"]));
            }
            set {
                this["Map_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elevation_GLOBE_Enabled {
            get {
                return ((bool)(this["Elevation_GLOBE_Enabled"]));
            }
            set {
                this["Elevation_GLOBE_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/database/")]
        public string Database_Update_URL {
            get {
                return ((string)(this["Database_Update_URL"]));
            }
            set {
                this["Database_Update_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Background_Update_OnStartup {
            get {
                return ((bool)(this["Background_Update_OnStartup"]));
            }
            set {
                this["Background_Update_OnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.Forms.FormWindowState General_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["General_WindowState"]));
            }
            set {
                this["General_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size General_WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["General_WindowSize"]));
            }
            set {
                this["General_WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point General_WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["General_WindowLocation"]));
            }
            set {
                this["General_WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Background_Update_Periodically {
            get {
                return ((bool)(this["Background_Update_Periodically"]));
            }
            set {
                this["Background_Update_Periodically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal Background_Update_Period {
            get {
                return ((decimal)(this["Background_Update_Period"]));
            }
            set {
                this["Background_Update_Period"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Tmp")]
        public string Tmp_Directory {
            get {
                return ((string)(this["Tmp_Directory"]));
            }
            set {
                this["Tmp_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Log")]
        public string Log_Directory {
            get {
                return ((string)(this["Log_Directory"]));
            }
            set {
                this["Log_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Locator_MaxLength {
            get {
                return ((decimal)(this["Locator_MaxLength"]));
            }
            set {
                this["Locator_MaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Locator_AutoLength {
            get {
                return ((bool)(this["Locator_AutoLength"]));
            }
            set {
                this["Locator_AutoLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Locator_SmallLettersForSubsquares {
            get {
                return ((bool)(this["Locator_SmallLettersForSubsquares"]));
            }
            set {
                this["Locator_SmallLettersForSubsquares"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AirScout.Watchlist Watchlist {
            get {
                return ((global::AirScout.Watchlist)(this["Watchlist"]));
            }
            set {
                this["Watchlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu")]
        public string Connectivity_URL {
            get {
                return ((string)(this["Connectivity_URL"]));
            }
            set {
                this["Connectivity_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Watchlist_SyncWithKST {
            get {
                return ((bool)(this["Watchlist_SyncWithKST"]));
            }
            set {
                this["Watchlist_SyncWithKST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Watchlist_Activated {
            get {
                return ((bool)(this["Watchlist_Activated"]));
            }
            set {
                this["Watchlist_Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://history.adsbexchange.com/Aircraftlist.json/")]
        public string Analysis_History_URL {
            get {
                return ((string)(this["Analysis_History_URL"]));
            }
            set {
                this["Analysis_History_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Analysis_History_Directory {
            get {
                return ((string)(this["Analysis_History_Directory"]));
            }
            set {
                this["Analysis_History_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-07-01")]
        public global::System.DateTime Analysis_History_Date {
            get {
                return ((global::System.DateTime)(this["Analysis_History_Date"]));
            }
            set {
                this["Analysis_History_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Analysis_History_ZIPFileName {
            get {
                return ((string)(this["Analysis_History_ZIPFileName"]));
            }
            set {
                this["Analysis_History_ZIPFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal Analysis_History_Stepwidth {
            get {
                return ((decimal)(this["Analysis_History_Stepwidth"]));
            }
            set {
                this["Analysis_History_Stepwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Analysis_History_LoadFileName {
            get {
                return ((string)(this["Analysis_History_LoadFileName"]));
            }
            set {
                this["Analysis_History_LoadFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Horizon_Plot_Map {
            get {
                return ((bool)(this["Horizon_Plot_Map"]));
            }
            set {
                this["Horizon_Plot_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elevation_GLOBE_EnableCache {
            get {
                return ((bool)(this["Elevation_GLOBE_EnableCache"]));
            }
            set {
                this["Elevation_GLOBE_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM3_EnableCache {
            get {
                return ((bool)(this["Elevation_SRTM3_EnableCache"]));
            }
            set {
                this["Elevation_SRTM3_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM1_EnableCache {
            get {
                return ((bool)(this["Elevation_SRTM1_EnableCache"]));
            }
            set {
                this["Elevation_SRTM1_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
Maidenhead locator system elvation tiles calculated by DL2ALF based on elevation data of the GLOBE project:

GLOBE Task Team and others (Hastings, David A., Paula K. Dunbar, Gerald M. Elphingstone, Mark Bootz, Hiroshi Murakami, Hiroshi Maruyama, 
Hiroshi Masaharu, Peter Holland, John Payne, Nevin A. Bryant, Thomas L. Logan, J.-P. Muller, Gunter Schreier, and John S. MacDonald), eds., 1999. 

The Global Land One-kilometer Base Elevation (GLOBE) Digital Elevation Model, 
Version 1.0. National Oceanic and Atmospheric Administration, National Geophysical Data Center, 325 Broadway, Boulder, Colorado 80305-3328, U.S.A. 

Digital data base on the World Wide Web (URL: http://www.ngdc.noaa.gov/mgg/topo/globe.html) and CD-ROMs. ")]
        public string Elevation_GLOBE_Copyright {
            get {
                return ((string)(this["Elevation_GLOBE_Copyright"]));
            }
            set {
                this["Elevation_GLOBE_Copyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nMaidenhead locator system elvation tiles calculated by DL2ALF based on elevatio" +
            "n data of the SRTM project:\r\n\r\nThis material is based on SRTM3 data V3.0 service" +
            "s provided by the OpenTopography Facility with support from the National Science" +
            " Foundation under NSF Award Numbers 1226353 & 1225810\r\nhttp://opentopo.sdsc.edu/" +
            "raster?opentopoID=OTSRTM.042013.4326.1\r\n\r\nThe Shuttle Radar Topography Mission (" +
            "SRTM) obtained elevation data on a near-global scale to generate the most comple" +
            "te high-resolution digital topographic database of Earth. SRTM consisted of a sp" +
            "ecially modified radar system that flew onboard the Space Shuttle Endeavour duri" +
            "ng an 11-day mission in February of 2000. SRTM is an international project spear" +
            "headed by the National Geospatial-Intelligence Agency (NGA) and the National Aer" +
            "onautics and Space Administration (NASA).\r\n\r\nVersion 3: Elimination of the voids" +
            " in the NASA SRTM DEM was the primary goal of a project under the NASA MEaSUREs " +
            "(Making Earth System Data Records for Use in Research Environments) Program. Ult" +
            "imately this was achieved by filling the voids with elevation data primarily fro" +
            "m the ASTER GDEM2 (Global Digital Elevation Model Version 2) and secondarily fro" +
            "m the USGS GMTED2010 elevation model or the USGS National Elevation Dataset (NED" +
            "). For more information on this dataset visit the LP DAAC NASA Shuttle Radar Top" +
            "ography Mission Global 3 arc second page.\r\n\r\nASTER GDEM is a product of NASA and" +
            " METI. See https://lpdaac.usgs.gov/dataset_discovery/aster\r\n\r\nMEaSUREs data and " +
            "products are available at no charge from the LP DAAC.See https://lpdaac.usgs.gov" +
            "/dataset_discovery/measures\r\n\r\n\r\n\r\n\r\n\r\n")]
        public string Elevation_SRTM3_Copyright {
            get {
                return ((string)(this["Elevation_SRTM3_Copyright"]));
            }
            set {
                this["Elevation_SRTM3_Copyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nMaidenhead locator system elvation tiles calculated by DL2ALF based on elevatio" +
            "n data of the SRTM project:\r\n\r\nThis material is based on SRTM1 data V3.0 service" +
            "s provided by the OpenTopography Facility with support from the National Science" +
            " Foundation under NSF Award Numbers 1226353 & 1225810\r\nhttp://opentopo.sdsc.edu/" +
            "raster?opentopoID=OTSRTM.082015.4326.1\r\n\r\nThe Shuttle Radar Topography Mission (" +
            "SRTM) obtained elevation data on a near-global scale to generate the most comple" +
            "te high-resolution digital topographic database of Earth. SRTM consisted of a sp" +
            "ecially modified radar system that flew onboard the Space Shuttle Endeavour duri" +
            "ng an 11-day mission in February of 2000. SRTM is an international project spear" +
            "headed by the National Geospatial-Intelligence Agency (NGA) and the National Aer" +
            "onautics and Space Administration (NASA).\r\nVersion 3: Elimination of the voids i" +
            "n the NASA SRTM DEM was the primary goal of a project under the NASA MEaSUREs (M" +
            "aking Earth System Data Records for Use in Research Environments) Program. Ultim" +
            "ately this was achieved by filling the voids with elevation data primarily from " +
            "the ASTER GDEM2 (Global Digital Elevation Model Version 2) and secondarily from " +
            "the USGS GMTED2010 elevation model or the USGS National Elevation Dataset (NED)." +
            " NASA SRTM V3.0 three-arc-second data are provided in two forms: (1) by three-by" +
            "-three averaging of the one arc-second samples, and (2) by extracting the middle" +
            " sample of those same three-by-three samples. For more information on this datas" +
            "et visit the LP DAAC NASA Shuttle Radar Topography Mission Global 1 arc second p" +
            "age.\r\nhttps://lpdaac.usgs.gov/dataset_discovery/measures/measures_products_table" +
            "/srtmgl1\r\n\r\nASTER GDEM is a product of NASA and METI. See https://lpdaac.usgs.go" +
            "v/dataset_discovery/aster\r\n\r\nMEaSUREs data and products are available at no char" +
            "ge from the LP DAAC.See https://lpdaac.usgs.gov/dataset_discovery/measures\r\n\r\n\r\n" +
            "\r\n\r\n")]
        public string Elevation_SRTM1_Copyright {
            get {
                return ((string)(this["Elevation_SRTM1_Copyright"]));
            }
            set {
                this["Elevation_SRTM1_Copyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double Path_MaxLength {
            get {
                return ((double)(this["Path_MaxLength"]));
            }
            set {
                this["Path_MaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Background_Calculations_Enable {
            get {
                return ((bool)(this["Background_Calculations_Enable"]));
            }
            set {
                this["Background_Calculations_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS StationsDatabase_Status {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["StationsDatabase_Status"]));
            }
            set {
                this["StationsDatabase_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AirScout.Core.BandSettings Path_Band_Settings {
            get {
                return ((global::AirScout.Core.BandSettings)(this["Path_Band_Settings"]));
            }
            set {
                this["Path_Band_Settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Background_Calculations_ThreadWait {
            get {
                return ((int)(this["Background_Calculations_ThreadWait"]));
            }
            set {
                this["Background_Calculations_ThreadWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> MyCalls {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["MyCalls"]));
            }
            set {
                this["MyCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_SmallMarkers {
            get {
                return ((bool)(this["Map_SmallMarkers"]));
            }
            set {
                this["Map_SmallMarkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public global::ScoutBase.Elevation.ELEVATIONMODEL ElevationModel {
            get {
                return ((global::ScoutBase.Elevation.ELEVATIONMODEL)(this["ElevationModel"]));
            }
            set {
                this["ElevationModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS AircraftDatabase_Status {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["AircraftDatabase_Status"]));
            }
            set {
                this["AircraftDatabase_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double Horizon_MaxDist {
            get {
                return ((double)(this["Horizon_MaxDist"]));
            }
            set {
                this["Horizon_MaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_GLOBE_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_GLOBE_DatabaseStatus"]));
            }
            set {
                this["Elevation_GLOBE_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_SRTM3_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_SRTM3_DatabaseStatus"]));
            }
            set {
                this["Elevation_SRTM3_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_SRTM1_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_SRTM1_DatabaseStatus"]));
            }
            set {
                this["Elevation_SRTM1_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public decimal AircraftDatabase_MaxSize {
            get {
                return ((decimal)(this["AircraftDatabase_MaxSize"]));
            }
            set {
                this["AircraftDatabase_MaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public decimal AircraftDatabase_MaxDaysLifetime {
            get {
                return ((decimal)(this["AircraftDatabase_MaxDaysLifetime"]));
            }
            set {
                this["AircraftDatabase_MaxDaysLifetime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000000")]
        public decimal AircraftDatabase_MaxCount {
            get {
                return ((decimal)(this["AircraftDatabase_MaxCount"]));
            }
            set {
                this["AircraftDatabase_MaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Analysis_CrossingHistory_WithSignalLevel {
            get {
                return ((bool)(this["Analysis_CrossingHistory_WithSignalLevel"]));
            }
            set {
                this["Analysis_CrossingHistory_WithSignalLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Analysis_CrossingHistory_AmbigousGap {
            get {
                return ((decimal)(this["Analysis_CrossingHistory_AmbigousGap"]));
            }
            set {
                this["Analysis_CrossingHistory_AmbigousGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Planes_KeepHistory {
            get {
                return ((bool)(this["Planes_KeepHistory"]));
            }
            set {
                this["Planes_KeepHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Database")]
        public string Database_Directory {
            get {
                return ((string)(this["Database_Directory"]));
            }
            set {
                this["Database_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ElevationData")]
        public string Elevation_Directory {
            get {
                return ((string)(this["Elevation_Directory"]));
            }
            set {
                this["Elevation_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Plugin")]
        public string Plugin_Directory {
            get {
                return ((string)(this["Plugin_Directory"]));
            }
            set {
                this["Plugin_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Planes_Interval {
            get {
                return ((int)(this["Planes_Interval"]));
            }
            set {
                this["Planes_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Planes_ExtendedPlausibilityCheck_Enabled {
            get {
                return ((bool)(this["Planes_ExtendedPlausibilityCheck_Enabled"]));
            }
            set {
                this["Planes_ExtendedPlausibilityCheck_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Planes_ExtendedPlausibilityCheck_MaxErrorDist {
            get {
                return ((int)(this["Planes_ExtendedPlausibilityCheck_MaxErrorDist"]));
            }
            set {
                this["Planes_ExtendedPlausibilityCheck_MaxErrorDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Planes_LogErrors {
            get {
                return ((bool)(this["Planes_LogErrors"]));
            }
            set {
                this["Planes_LogErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/downloads/AirScoutPlugins/")]
        public string Plugins_Update_URL {
            get {
                return ((string)(this["Plugins_Update_URL"]));
            }
            set {
                this["Plugins_Update_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AirScout_Instance_ID {
            get {
                return ((string)(this["AirScout_Instance_ID"]));
            }
            set {
                this["AirScout_Instance_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/register.php")]
        public string AirScout_Register_URL {
            get {
                return ((string)(this["AirScout_Register_URL"]));
            }
            set {
                this["AirScout_Register_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/getkey.php")]
        public string AirScout_GetKey_URL {
            get {
                return ((string)(this["AirScout_GetKey_URL"]));
            }
            set {
                this["AirScout_GetKey_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/upload_location.php")]
        public string AirScout_UploadLocation_URL {
            get {
                return ((string)(this["AirScout_UploadLocation_URL"]));
            }
            set {
                this["AirScout_UploadLocation_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/upload_qrv.php")]
        public string AirScout_UploadQRV_URL {
            get {
                return ((string)(this["AirScout_UploadQRV_URL"]));
            }
            set {
                this["AirScout_UploadQRV_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AirScout_Device_ID {
            get {
                return ((string)(this["AirScout_Device_ID"]));
            }
            set {
                this["AirScout_Device_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AirScout\\AircraftData")]
        public string AircraftDatabase_Directory {
            get {
                return ((string)(this["AircraftDatabase_Directory"]));
            }
            set {
                this["AircraftDatabase_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ScoutBase\\StationData")]
        public string StationsDatabase_Directory {
            get {
                return ((string)(this["StationsDatabase_Directory"]));
            }
            set {
                this["StationsDatabase_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ScoutBase\\ElevationData")]
        public string ElevationDatabase_Directory {
            get {
                return ((string)(this["ElevationDatabase_Directory"]));
            }
            set {
                this["ElevationDatabase_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ScoutBase\\PropagationData")]
        public string PropagationDatabase_Directory {
            get {
                return ((string)(this["PropagationDatabase_Directory"]));
            }
            set {
                this["PropagationDatabase_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_LabelCalls {
            get {
                return ((bool)(this["Map_LabelCalls"]));
            }
            set {
                this["Map_LabelCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal Charts_FontSize {
            get {
                return ((decimal)(this["Charts_FontSize"]));
            }
            set {
                this["Charts_FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Location_RestrictToAreaOfInterest {
            get {
                return ((bool)(this["Location_RestrictToAreaOfInterest"]));
            }
            set {
                this["Location_RestrictToAreaOfInterest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01")]
        public global::System.DateTime StationsDatabase_TimeStamp {
            get {
                return ((global::System.DateTime)(this["StationsDatabase_TimeStamp"]));
            }
            set {
                this["StationsDatabase_TimeStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_Preloader_Enabled {
            get {
                return ((bool)(this["Map_Preloader_Enabled"]));
            }
            set {
                this["Map_Preloader_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Map_Preloader_MinZoom {
            get {
                return ((decimal)(this["Map_Preloader_MinZoom"]));
            }
            set {
                this["Map_Preloader_MinZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public decimal Map_Preloader_MaxZoom {
            get {
                return ((decimal)(this["Map_Preloader_MaxZoom"]));
            }
            set {
                this["Map_Preloader_MaxZoom"] = value;
            }
        }
    }
}
