//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainScout.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenStreetMap")]
        public string Map_Provider {
            get {
                return ((string)(this["Map_Provider"]));
            }
            set {
                this["Map_Provider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL2ALF")]
        public string MyCall {
            get {
                return ((string)(this["MyCall"]));
            }
            set {
                this["MyCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.937067")]
        public double MyLat {
            get {
                return ((double)(this["MyLat"]));
            }
            set {
                this["MyLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.68327")]
        public double MyLon {
            get {
                return ((double)(this["MyLon"]));
            }
            set {
                this["MyLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JO50IW")]
        public string MyLoc {
            get {
                return ((string)(this["MyLoc"]));
            }
            set {
                this["MyLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ScpLat {
            get {
                return ((double)(this["ScpLat"]));
            }
            set {
                this["ScpLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ScpLon {
            get {
                return ((double)(this["ScpLon"]));
            }
            set {
                this["ScpLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScpLoc {
            get {
                return ((string)(this["ScpLoc"]));
            }
            set {
                this["ScpLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\GLOBE")]
        public string Elevation_GLOBE_DataPath {
            get {
                return ((string)(this["Elevation_GLOBE_DataPath"]));
            }
            set {
                this["Elevation_GLOBE_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM1")]
        public string Elevation_SRTM1_DataPath {
            get {
                return ((string)(this["Elevation_SRTM1_DataPath"]));
            }
            set {
                this["Elevation_SRTM1_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationData\\SRTM3")]
        public string Elevation_SRTM3_DataPath {
            get {
                return ((string)(this["Elevation_SRTM3_DataPath"]));
            }
            set {
                this["Elevation_SRTM3_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elevation_GLOBE_Enabled {
            get {
                return ((bool)(this["Elevation_GLOBE_Enabled"]));
            }
            set {
                this["Elevation_GLOBE_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM1_Enabled {
            get {
                return ((bool)(this["Elevation_SRTM1_Enabled"]));
            }
            set {
                this["Elevation_SRTM1_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elevation_SRTM3_Enabled {
            get {
                return ((bool)(this["Elevation_SRTM3_Enabled"]));
            }
            set {
                this["Elevation_SRTM3_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Path_Cubic_Spline {
            get {
                return ((bool)(this["Path_Cubic_Spline"]));
            }
            set {
                this["Path_Cubic_Spline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double Path_Default_F1_Clearance {
            get {
                return ((double)(this["Path_Default_F1_Clearance"]));
            }
            set {
                this["Path_Default_F1_Clearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Ground_Clearance {
            get {
                return ((double)(this["Path_Default_Ground_Clearance"]));
            }
            set {
                this["Path_Default_Ground_Clearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.33")]
        public double Path_Default_K_Factor {
            get {
                return ((double)(this["Path_Default_K_Factor"]));
            }
            set {
                this["Path_Default_K_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double Path_Default_Max_Distance {
            get {
                return ((double)(this["Path_Default_Max_Distance"]));
            }
            set {
                this["Path_Default_Max_Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Max_Elevation {
            get {
                return ((double)(this["Path_Default_Max_Elevation"]));
            }
            set {
                this["Path_Default_Max_Elevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Path_Default_Max_Squint {
            get {
                return ((double)(this["Path_Default_Max_Squint"]));
            }
            set {
                this["Path_Default_Max_Squint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Path_NearFieldSuppression {
            get {
                return ((double)(this["Path_NearFieldSuppression"]));
            }
            set {
                this["Path_NearFieldSuppression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Path_StepWidth {
            get {
                return ((int)(this["Path_StepWidth"]));
            }
            set {
                this["Path_StepWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_BandSettings {
            get {
                return ((string)(this["Path_BandSettings"]));
            }
            set {
                this["Path_BandSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizon\\")]
        public string Horizon_DataPath {
            get {
                return ((string)(this["Horizon_DataPath"]));
            }
            set {
                this["Horizon_DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double Scatter_MaxRadius {
            get {
                return ((double)(this["Scatter_MaxRadius"]));
            }
            set {
                this["Scatter_MaxRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Scatter_MinRadius {
            get {
                return ((double)(this["Scatter_MinRadius"]));
            }
            set {
                this["Scatter_MinRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double Scatter_MaxAngle {
            get {
                return ((double)(this["Scatter_MaxAngle"]));
            }
            set {
                this["Scatter_MaxAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public double Scatter_MinHeight {
            get {
                return ((double)(this["Scatter_MinHeight"]));
            }
            set {
                this["Scatter_MinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public double Scatter_MaxHeight {
            get {
                return ((double)(this["Scatter_MaxHeight"]));
            }
            set {
                this["Scatter_MaxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DXCall {
            get {
                return ((string)(this["DXCall"]));
            }
            set {
                this["DXCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DXLat {
            get {
                return ((double)(this["DXLat"]));
            }
            set {
                this["DXLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DXLon {
            get {
                return ((double)(this["DXLon"]));
            }
            set {
                this["DXLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DXLoc {
            get {
                return ((string)(this["DXLoc"]));
            }
            set {
                this["DXLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database\\calls.bin")]
        public string Database_Filename {
            get {
                return ((string)(this["Database_Filename"]));
            }
            set {
                this["Database_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MyElevation {
            get {
                return ((double)(this["MyElevation"]));
            }
            set {
                this["MyElevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double MyHeight {
            get {
                return ((double)(this["MyHeight"]));
            }
            set {
                this["MyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public decimal MinLat {
            get {
                return ((decimal)(this["MinLat"]));
            }
            set {
                this["MinLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal MaxLat {
            get {
                return ((decimal)(this["MaxLat"]));
            }
            set {
                this["MaxLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public decimal MinLon {
            get {
                return ((decimal)(this["MinLon"]));
            }
            set {
                this["MinLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal MaxLon {
            get {
                return ((decimal)(this["MaxLon"]));
            }
            set {
                this["MaxLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B10G")]
        public global::ScoutBase.Core.BAND CurrentBand {
            get {
                return ((global::ScoutBase.Core.BAND)(this["CurrentBand"]));
            }
            set {
                this["CurrentBand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SRTM3")]
        public global::ScoutBase.Elevation.ELEVATIONMODEL CurrentElevationModel {
            get {
                return ((global::ScoutBase.Elevation.ELEVATIONMODEL)(this["CurrentElevationModel"]));
            }
            set {
                this["CurrentElevationModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::RainScout.BandSettings Band_Settings {
            get {
                return ((global::RainScout.BandSettings)(this["Band_Settings"]));
            }
            set {
                this["Band_Settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentRadar {
            get {
                return ((string)(this["CurrentRadar"]));
            }
            set {
                this["CurrentRadar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_VisibleScpOnly {
            get {
                return ((bool)(this["Filter_VisibleScpOnly"]));
            }
            set {
                this["Filter_VisibleScpOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal Filter_MinDistance {
            get {
                return ((decimal)(this["Filter_MinDistance"]));
            }
            set {
                this["Filter_MinDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal Filter_MaxDistance {
            get {
                return ((decimal)(this["Filter_MaxDistance"]));
            }
            set {
                this["Filter_MaxDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Radar_Opacity {
            get {
                return ((int)(this["Radar_Opacity"]));
            }
            set {
                this["Radar_Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_Intensity {
            get {
                return ((bool)(this["Map_Intensity"]));
            }
            set {
                this["Map_Intensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_CloudTops {
            get {
                return ((bool)(this["Map_CloudTops"]));
            }
            set {
                this["Map_CloudTops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Map_Lightning {
            get {
                return ((bool)(this["Map_Lightning"]));
            }
            set {
                this["Map_Lightning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_Bounds {
            get {
                return ((bool)(this["Map_Bounds"]));
            }
            set {
                this["Map_Bounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_Horizons {
            get {
                return ((bool)(this["Map_Horizons"]));
            }
            set {
                this["Map_Horizons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Map_Distances {
            get {
                return ((bool)(this["Map_Distances"]));
            }
            set {
                this["Map_Distances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ScpCloudTop {
            get {
                return ((double)(this["ScpCloudTop"]));
            }
            set {
                this["ScpCloudTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS StationsDatabase_Status {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["StationsDatabase_Status"]));
            }
            set {
                this["StationsDatabase_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Background_Update_OnStartup {
            get {
                return ((bool)(this["Background_Update_OnStartup"]));
            }
            set {
                this["Background_Update_OnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Location_RestrictToAreaOfInterest {
            get {
                return ((bool)(this["Location_RestrictToAreaOfInterest"]));
            }
            set {
                this["Location_RestrictToAreaOfInterest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_GLOBE_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_GLOBE_DatabaseStatus"]));
            }
            set {
                this["Elevation_GLOBE_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_SRTM3_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_SRTM3_DatabaseStatus"]));
            }
            set {
                this["Elevation_SRTM3_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNDEFINED")]
        public global::System.Data.SQLite.DATABASESTATUS Elevation_SRTM1_DatabaseStatus {
            get {
                return ((global::System.Data.SQLite.DATABASESTATUS)(this["Elevation_SRTM1_DatabaseStatus"]));
            }
            set {
                this["Elevation_SRTM1_DatabaseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elevation_GLOBE_EnableCache {
            get {
                return ((bool)(this["Elevation_GLOBE_EnableCache"]));
            }
            set {
                this["Elevation_GLOBE_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM3_EnableCache {
            get {
                return ((bool)(this["Elevation_SRTM3_EnableCache"]));
            }
            set {
                this["Elevation_SRTM3_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Elevation_SRTM1_EnableCache {
            get {
                return ((bool)(this["Elevation_SRTM1_EnableCache"]));
            }
            set {
                this["Elevation_SRTM1_EnableCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RainScout_Instance_ID {
            get {
                return ((string)(this["RainScout_Instance_ID"]));
            }
            set {
                this["RainScout_Instance_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/getkey.php")]
        public string AirScout_GetKey_URL {
            get {
                return ((string)(this["AirScout_GetKey_URL"]));
            }
            set {
                this["AirScout_GetKey_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/register.php")]
        public string AirScout_Register_URL {
            get {
                return ((string)(this["AirScout_Register_URL"]));
            }
            set {
                this["AirScout_Register_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/upload_location.php")]
        public string AirScout_UploadLocation_URL {
            get {
                return ((string)(this["AirScout_UploadLocation_URL"]));
            }
            set {
                this["AirScout_UploadLocation_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.airscout.eu/usr/upload_qrv.php")]
        public string AirScout_UploadQRV_URL {
            get {
                return ((string)(this["AirScout_UploadQRV_URL"]));
            }
            set {
                this["AirScout_UploadQRV_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RainScout_Device_ID {
            get {
                return ((string)(this["RainScout_Device_ID"]));
            }
            set {
                this["RainScout_Device_ID"] = value;
            }
        }
    }
}
