//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirScout.PlaneFeeds.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://droidapp.pinkfroot.com/APPAPIDROID/v7/planeUpdateFAA.php?routetype=IATA&FA" +
            "A=1&bounds=%MAXLAT%,%MINLAT%,%MINLON%,%MAXLON%")]
        public string PF_URL {
            get {
                return ((string)(this["PF_URL"]));
            }
            set {
                this["PF_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int PF_Interval {
            get {
                return ((int)(this["PF_Interval"]));
            }
            set {
                this["PF_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Generic Info.")]
        public string Generic_Info {
            get {
                return ((string)(this["Generic_Info"]));
            }
            set {
                this["Generic_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web feed from www.planefinder.net")]
        public string PF_Info {
            get {
                return ((string)(this["PF_Info"]));
            }
            set {
                this["PF_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Generic]           Dummy Plane Feed")]
        public string Generic_Name {
            get {
                return ((string)(this["Generic_Name"]));
            }
            set {
                this["Generic_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           www.planefinder.net")]
        public string PF_Name {
            get {
                return ((string)(this["PF_Name"]));
            }
            set {
                this["PF_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This plane feed is being fetched from an Internet server via Deep Link 
technology  (see http://en.wikipedia.org/wiki/Deep_link). 

The use is not intended by the website owners and could be changed in URL and data format frequently and without further notice. 
Furthermore, it might cause legal issues in some countries. 

By clicking on ""Accept"" you understand that you are 

                           DOING THAT ON YOUR OWN RISK

The auhor of this software will not be responsible in any case.")]
        public string PF_Disclaimer {
            get {
                return ((string)(this["PF_Disclaimer"]));
            }
            set {
                this["PF_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PF_Disclaimer_Accepted {
            get {
                return ((string)(this["PF_Disclaimer_Accepted"]));
            }
            set {
                this["PF_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Generic_Disclaimer_Accepted {
            get {
                return ((string)(this["Generic_Disclaimer_Accepted"]));
            }
            set {
                this["Generic_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This plane feed is a dummy plane feed generating random plane positions. 

USE THIS FEED FOR DEMONSTRATION PURPOSE ONLY!

The feed will run without fetching any data from the Internet. 
Please do not mix it with other feeds as confusion may occur with live data.
The call signs generated will look like ""RND0001"", ""RND0002"" etc.")]
        public string Generic_Disclaimer {
            get {
                return ((string)(this["Generic_Disclaimer"]));
            }
            set {
                this["Generic_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9880/planes.json")]
        public string AS_URL {
            get {
                return ((string)(this["AS_URL"]));
            }
            set {
                this["AS_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AS_Interval {
            get {
                return ((int)(this["AS_Interval"]));
            }
            set {
                this["AS_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           AirScout Web Server")]
        public string AS_Name {
            get {
                return ((string)(this["AS_Name"]));
            }
            set {
                this["AS_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AS_Disclaimer {
            get {
                return ((string)(this["AS_Disclaimer"]));
            }
            set {
                this["AS_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AS_Disclaimer_Accepted {
            get {
                return ((string)(this["AS_Disclaimer_Accepted"]));
            }
            set {
                this["AS_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web feed from another AirScout server.")]
        public string AS_Info {
            get {
                return ((string)(this["AS_Info"]));
            }
            set {
                this["AS_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FJ_Disclaimer {
            get {
                return ((string)(this["FJ_Disclaimer"]));
            }
            set {
                this["FJ_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FJ_Disclaimer_Accepted {
            get {
                return ((string)(this["FJ_Disclaimer_Accepted"]));
            }
            set {
                this["FJ_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int FJ_Interval {
            get {
                return ((int)(this["FJ_Interval"]));
            }
            set {
                this["FJ_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reads plane positions out of a JSON file.")]
        public string FJ_Info {
            get {
                return ((string)(this["FJ_Info"]));
            }
            set {
                this["FJ_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[FileFeed]          JSON file")]
        public string FJ_Name {
            get {
                return ((string)(this["FJ_Name"]));
            }
            set {
                this["FJ_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("planes.json")]
        public string FJ_Path {
            get {
                return ((string)(this["FJ_Path"]));
            }
            set {
                this["FJ_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[RawData]           ADSBSharp data ")]
        public string ADSB_Name {
            get {
                return ((string)(this["ADSB_Name"]));
            }
            set {
                this["ADSB_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raw data feed from simple ADS-B receivers (DVB-T dongles).\r\nUse this feed thogeth" +
            "er with ADSBSharp.\r\n\r\n\r\n")]
        public string ADSB_Info {
            get {
                return ((string)(this["ADSB_Info"]));
            }
            set {
                this["ADSB_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADSB_Disclaimer {
            get {
                return ((string)(this["ADSB_Disclaimer"]));
            }
            set {
                this["ADSB_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADSB_Disclaimer_Accepted {
            get {
                return ((string)(this["ADSB_Disclaimer_Accepted"]));
            }
            set {
                this["ADSB_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ADSB_Server {
            get {
                return ((string)(this["ADSB_Server"]));
            }
            set {
                this["ADSB_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47806")]
        public int ADSB_Port {
            get {
                return ((int)(this["ADSB_Port"]));
            }
            set {
                this["ADSB_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ADSB_Interval {
            get {
                return ((int)(this["ADSB_Interval"]));
            }
            set {
                this["ADSB_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ADSB_Binary {
            get {
                return ((bool)(this["ADSB_Binary"]));
            }
            set {
                this["ADSB_Binary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ADSB_Report_Messages {
            get {
                return ((bool)(this["ADSB_Report_Messages"]));
            }
            set {
                this["ADSB_Report_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ADSB_MarkLocal {
            get {
                return ((bool)(this["ADSB_MarkLocal"]));
            }
            set {
                this["ADSB_MarkLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[RawData]           RTL1090 data ")]
        public string RTL_Name {
            get {
                return ((string)(this["RTL_Name"]));
            }
            set {
                this["RTL_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raw data feed from simple ADS-B receivers (DVB-T dongles).\r\nUse this feed togethe" +
            "r with RTL1090.exe.\r\n\r\nFeed software must output raw data either binary or ASCII" +
            " format via TCP.\r\n\r\n\r\n")]
        public string RTL_Info {
            get {
                return ((string)(this["RTL_Info"]));
            }
            set {
                this["RTL_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RTL_Disclaimer {
            get {
                return ((string)(this["RTL_Disclaimer"]));
            }
            set {
                this["RTL_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RTL_Disclaimer_Accepted {
            get {
                return ((string)(this["RTL_Disclaimer_Accepted"]));
            }
            set {
                this["RTL_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string RTL_Server {
            get {
                return ((string)(this["RTL_Server"]));
            }
            set {
                this["RTL_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31001")]
        public int RTL_Port {
            get {
                return ((int)(this["RTL_Port"]));
            }
            set {
                this["RTL_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RTL_Interval {
            get {
                return ((int)(this["RTL_Interval"]));
            }
            set {
                this["RTL_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RTL_Binary {
            get {
                return ((bool)(this["RTL_Binary"]));
            }
            set {
                this["RTL_Binary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RTL_Report_Messages {
            get {
                return ((bool)(this["RTL_Report_Messages"]));
            }
            set {
                this["RTL_Report_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RTL_MarkLocal {
            get {
                return ((bool)(this["RTL_MarkLocal"]));
            }
            set {
                this["RTL_MarkLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This plane feed is being fetched from an Internet server via Deep Link 
technology  (see http://en.wikipedia.org/wiki/Deep_link). 

The use is not intended by the website owners and could be changed in URL and data format frequently and without further notice. 
Furthermore, it might cause legal issues in some countries. 

By clicking on ""Accept"" you understand that you are 

                           DOING THAT ON YOUR OWN RISK

The auhor of this software will not be responsible in any case.")]
        public string AJ_Disclaimer {
            get {
                return ((string)(this["AJ_Disclaimer"]));
            }
            set {
                this["AJ_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AJ_Disclaimer_Accepted {
            get {
                return ((string)(this["AJ_Disclaimer_Accepted"]));
            }
            set {
                this["AJ_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JSON file from web feed with auto detection of content")]
        public string AJ_Info {
            get {
                return ((string)(this["AJ_Info"]));
            }
            set {
                this["AJ_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AJ_Interval {
            get {
                return ((int)(this["AJ_Interval"]));
            }
            set {
                this["AJ_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           Automatic JSON file detection")]
        public string AJ_Name {
            get {
                return ((string)(this["AJ_Name"]));
            }
            set {
                this["AJ_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AJ_URL {
            get {
                return ((string)(this["AJ_URL"]));
            }
            set {
                this["AJ_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_UTC {
            get {
                return ((int)(this["AJ_Index_UTC"]));
            }
            set {
                this["AJ_Index_UTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Hex {
            get {
                return ((int)(this["AJ_Index_Hex"]));
            }
            set {
                this["AJ_Index_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Call {
            get {
                return ((int)(this["AJ_Index_Call"]));
            }
            set {
                this["AJ_Index_Call"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Lat {
            get {
                return ((int)(this["AJ_Index_Lat"]));
            }
            set {
                this["AJ_Index_Lat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Lon {
            get {
                return ((int)(this["AJ_Index_Lon"]));
            }
            set {
                this["AJ_Index_Lon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Alt {
            get {
                return ((int)(this["AJ_Index_Alt"]));
            }
            set {
                this["AJ_Index_Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Speed {
            get {
                return ((int)(this["AJ_Index_Speed"]));
            }
            set {
                this["AJ_Index_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Reg {
            get {
                return ((int)(this["AJ_Index_Reg"]));
            }
            set {
                this["AJ_Index_Reg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Track {
            get {
                return ((int)(this["AJ_Index_Track"]));
            }
            set {
                this["AJ_Index_Track"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Type {
            get {
                return ((int)(this["AJ_Index_Type"]));
            }
            set {
                this["AJ_Index_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AJ_Min_Elements {
            get {
                return ((int)(this["AJ_Min_Elements"]));
            }
            set {
                this["AJ_Min_Elements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AJ_Min_Planes {
            get {
                return ((int)(this["AJ_Min_Planes"]));
            }
            set {
                this["AJ_Min_Planes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Squawk {
            get {
                return ((int)(this["AJ_Index_Squawk"]));
            }
            set {
                this["AJ_Index_Squawk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AJ_AutoIndex {
            get {
                return ((bool)(this["AJ_AutoIndex"]));
            }
            set {
                this["AJ_AutoIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Radar {
            get {
                return ((int)(this["AJ_Index_Radar"]));
            }
            set {
                this["AJ_Index_Radar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Flight {
            get {
                return ((int)(this["AJ_Index_Flight"]));
            }
            set {
                this["AJ_Index_Flight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AJ_Index_Route {
            get {
                return ((int)(this["AJ_Index_Route"]));
            }
            set {
                this["AJ_Index_Route"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This plane feed is being fetched from Flightradar24.com  website
after checking your valid premium accout.
Even though AirScout is checking your account status online:
This service is not authorized by Fligthradar24 and is not guaranteed 
to work under all circumstances.Paying for a FR24 premium account
does not automatically grants the right to access the data via AirScout.

By clicking on ""Accept"" you understand that you are 

                           DOING THAT ON YOUR OWN RISK

The auhor of this software will not be responsible in any case.")]
        public string FR_Disclaimer {
            get {
                return ((string)(this["FR_Disclaimer"]));
            }
            set {
                this["FR_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FR_Disclaimer_Accepted {
            get {
                return ((string)(this["FR_Disclaimer_Accepted"]));
            }
            set {
                this["FR_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web feed from www.flightradar24.com. You need a premim account to use this servic" +
            "e.")]
        public string FR_Info {
            get {
                return ((string)(this["FR_Info"]));
            }
            set {
                this["FR_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int FR_Interval {
            get {
                return ((int)(this["FR_Interval"]));
            }
            set {
                this["FR_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           www.flightradar24.com")]
        public string FR_Name {
            get {
                return ((string)(this["FR_Name"]));
            }
            set {
                this["FR_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FR_Login_User {
            get {
                return ((string)(this["FR_Login_User"]));
            }
            set {
                this["FR_Login_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FR_Login_Password {
            get {
                return ((string)(this["FR_Login_Password"]));
            }
            set {
                this["FR_Login_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Web feed from Virtual Radar Server")]
        public string VR_Info {
            get {
                return ((string)(this["VR_Info"]));
            }
            set {
                this["VR_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]           Virtual Radar Server")]
        public string VR_Name {
            get {
                return ((string)(this["VR_Name"]));
            }
            set {
                this["VR_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VR_Disclaimer {
            get {
                return ((string)(this["VR_Disclaimer"]));
            }
            set {
                this["VR_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VR_Disclaimer_Accepted {
            get {
                return ((string)(this["VR_Disclaimer_Accepted"]));
            }
            set {
                this["VR_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int VR_Interval {
            get {
                return ((int)(this["VR_Interval"]));
            }
            set {
                this["VR_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://public-api.adsbexchange.com/VirtualRadar/AircraftList.json?fNBnd=%MAXLAT%&" +
            "fSBnd=%MINLAT%&fWBnd=%MINLON%&fEBnd=%MAXLON%&fAltL=%MINALTFT%&fAltU=%MAXALTFT%")]
        public string VR_URL {
            get {
                return ((string)(this["VR_URL"]));
            }
            set {
                this["VR_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PF_SaveToFile {
            get {
                return ((bool)(this["PF_SaveToFile"]));
            }
            set {
                this["PF_SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FR_SaveToFile {
            get {
                return ((bool)(this["FR_SaveToFile"]));
            }
            set {
                this["FR_SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AJ_SaveToFile {
            get {
                return ((bool)(this["AJ_SaveToFile"]));
            }
            set {
                this["AJ_SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VR_SaveToFile {
            get {
                return ((bool)(this["VR_SaveToFile"]));
            }
            set {
                this["VR_SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WF_Disclaimer {
            get {
                return ((string)(this["WF_Disclaimer"]));
            }
            set {
                this["WF_Disclaimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WF_Disclaimer_Accepted {
            get {
                return ((string)(this["WF_Disclaimer_Accepted"]));
            }
            set {
                this["WF_Disclaimer_Accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Universal Web Feed")]
        public string WF_Info {
            get {
                return ((string)(this["WF_Info"]));
            }
            set {
                this["WF_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int WF_Interval {
            get {
                return ((int)(this["WF_Interval"]));
            }
            set {
                this["WF_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[WebFeed]     Universal Web Feed")]
        public string WF_Name {
            get {
                return ((string)(this["WF_Name"]));
            }
            set {
                this["WF_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WF_SaveToFile {
            get {
                return ((bool)(this["WF_SaveToFile"]));
            }
            set {
                this["WF_SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WF_URL {
            get {
                return ((string)(this["WF_URL"]));
            }
            set {
                this["WF_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Call {
            get {
                return ((int)(this["WF_Index_Call"]));
            }
            set {
                this["WF_Index_Call"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Alt {
            get {
                return ((int)(this["WF_Index_Alt"]));
            }
            set {
                this["WF_Index_Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Flight {
            get {
                return ((int)(this["WF_Index_Flight"]));
            }
            set {
                this["WF_Index_Flight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Hex {
            get {
                return ((int)(this["WF_Index_Hex"]));
            }
            set {
                this["WF_Index_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Lat {
            get {
                return ((int)(this["WF_Index_Lat"]));
            }
            set {
                this["WF_Index_Lat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Lon {
            get {
                return ((int)(this["WF_Index_Lon"]));
            }
            set {
                this["WF_Index_Lon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Radar {
            get {
                return ((int)(this["WF_Index_Radar"]));
            }
            set {
                this["WF_Index_Radar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Reg {
            get {
                return ((int)(this["WF_Index_Reg"]));
            }
            set {
                this["WF_Index_Reg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Route {
            get {
                return ((int)(this["WF_Index_Route"]));
            }
            set {
                this["WF_Index_Route"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Speed {
            get {
                return ((int)(this["WF_Index_Speed"]));
            }
            set {
                this["WF_Index_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Squawk {
            get {
                return ((int)(this["WF_Index_Squawk"]));
            }
            set {
                this["WF_Index_Squawk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Track {
            get {
                return ((int)(this["WF_Index_Track"]));
            }
            set {
                this["WF_Index_Track"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_Type {
            get {
                return ((int)(this["WF_Index_Type"]));
            }
            set {
                this["WF_Index_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Index_UTC {
            get {
                return ((int)(this["WF_Index_UTC"]));
            }
            set {
                this["WF_Index_UTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Min_Elements {
            get {
                return ((int)(this["WF_Min_Elements"]));
            }
            set {
                this["WF_Min_Elements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WF_Min_Planes {
            get {
                return ((int)(this["WF_Min_Planes"]));
            }
            set {
                this["WF_Min_Planes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WF_AutoIndex {
            get {
                return ((bool)(this["WF_AutoIndex"]));
            }
            set {
                this["WF_AutoIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VR_ExtendedPlausibilityCheck {
            get {
                return ((bool)(this["VR_ExtendedPlausibilityCheck"]));
            }
            set {
                this["VR_ExtendedPlausibilityCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double VR_EstimatedPosition_MaxError {
            get {
                return ((double)(this["VR_EstimatedPosition_MaxError"]));
            }
            set {
                this["VR_EstimatedPosition_MaxError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VR_LogErrors {
            get {
                return ((bool)(this["VR_LogErrors"]));
            }
            set {
                this["VR_LogErrors"] = value;
            }
        }
    }
}
